auto-detect curl or wget; error if neither exists

diff --git a/zoom-upd b/zoom-upd
--- a/zoom-upd
+++ b/zoom-upd
@@ -8,8 +8,24 @@ ubuntu=0
 redhat=0
 unk=0
 
-rzv=$(wget -O - -U "Mozilla/5.0 (X11; Linux x86_64)" --quiet \
-	https://zoom.us/download | grep -E 'linux-ver-text.*Version' | sed 's/.*Version //; s|</span>.*||;' )
+WGET=$(which wget 2>/dev/null)
+CURL=$(which curl 2>/dev/null)
+if [ "${WGET}" -a -x "${WGET}" ]
+then
+	FETCH="wget --quiet"
+	UA="-U"
+	OUT="-O"
+elif [ "${CURL}" -a -x "${CURL}" ]
+then
+	FETCH="curl --silent"
+	UA="-A"
+	OUT="-o"
+else
+	echo "wget or curl is required"
+	exit 1
+fi
+
+rzv=$(${FETCH} ${UA} "Mozilla/5.0 (X11; Linux x86_64)" ${OUT} - https://zoom.us/download | grep -E 'linux-ver-text.*Version' | sed 's/.*Version //; s|</span>.*||;' )
 
 # expand the detection for different OS's as needed
 if [ -n "$(which apt 2>/dev/null)" ]
@@ -30,13 +46,13 @@ fi
 if [ 1 -eq ${ubuntu:-0} ]
 then
 	lzv=$(dpkg -l zoom 2>&1 | grep ^ii | awk '{print $3}')
-	dpkg --compare-versions $lzv lt $rzv
+	dpkg --compare-versions ${lzv:-0} lt ${rzv:-0}
 	if [ $? -eq 0 ]
 	then
 		echo "Upgrade needed"
-		wget -O /tmp/zoom-${rzv}-amd64.deb https://zoom.us/client/latest/zoom_amd64.deb
-		sudo dpkg -i /tmp/zoom-${rzv}-amd64.deb
-		rm -i /tmp/zoom-${rzv}-amd64.deb
+		${FETCH} ${UA} "Mozilla/5.0 (X11; Linux x86_64)" ${OUT}  /tmp/zoom-${rzv:-0}-amd64.deb https://zoom.us/client/latest/zoom_amd64.deb
+		sudo dpkg -i /tmp/zoom-${rzv:-0}-amd64.deb
+		rm -i /tmp/zoom-${rzv:-0}-amd64.deb
 	else
 		echo "no newer version available"
 	fi
@@ -45,29 +61,29 @@ then
 	lzv=$(rpm -q zoom --info 2>&1 | grep Version | cut -f2 -d:)
 	# need to compare current version vs remote version
 	
-	wget -O /tmp/zoom-${rzv}-x86_64.rpm https://zoom.us/client/latest/zoom_x86_64.rpm
+	${FETCH} ${UA} "Mozilla/5.0 (X11; Linux x86_64)" ${OUT}  /tmp/zoom-${rzv:-0}-x86_64.rpm https://zoom.us/client/latest/zoom_x86_64.rpm
 
 	# because we might need dependencies
-	sudo yum install /tmp/zoom-${rzv}-x86_64.rpm
+	sudo yum install /tmp/zoom-${rzv:-0}-x86_64.rpm
 
-	rm -i /tmp/zoom-${rzv}-x86_64.rpm
+	rm -i /tmp/zoom-${rzv:-0}-x86_64.rpm
 elif [ 1 -eq ${arch:-0} ]
 then
 	# Need to detect the current version
 	# need to compare current version vs remote version
 	
-	wget -O /tmp/zoom-${rzv}-x86_64.pkg.tar.xz https://zoom.us/client/latest/zoom_x86_64.pkg.tar.xz
+	${FETCH} ${UA} "Mozilla/5.0 (X11; Linux x86_64)" ${OUT}  /tmp/zoom-${rzv:-0}-x86_64.pkg.tar.xz https://zoom.us/client/latest/zoom_x86_64.pkg.tar.xz
 
 	# This grabs dependencies
-	pacman -U /tmp/zoom-${rzv}-x86_64.pkg.tar.xz
+	pacman -U /tmp/zoom-${rzv:-0}-x86_64.pkg.tar.xz
 
-	rm -i /tmp/zoom-${rzv}-x86_64.pkg.tar.xz
+	rm -i /tmp/zoom-${rzv:-0}-x86_64.pkg.tar.xz
 elif [ 1 -eq ${unk:-0} ]
 then
 	# Need to detect the current version
 	# need to compare current version vs remote version
 	
-	wget -O /tmp/zoom-${rzv}-x86_64.tar.xz https://zoom.us/client/latest/zoom_x86_64.tar.xz
+	${FETCH} ${UA} "Mozilla/5.0 (X11; Linux x86_64)" ${OUT}  /tmp/zoom-${rzv:-0}-x86_64.tar.xz https://zoom.us/client/latest/zoom_x86_64.tar.xz
 	echo "You'll need to manually install from the package"
 else
 	echo "Can't determine version for automatic upgrade"
